// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Workers.WrkNFe.Context;

namespace Workers.Migrations
{
    [DbContext(typeof(NFeContext))]
    [Migration("20200618145845_upd1")]
    partial class upd1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Workers.WrkNFe.Models.NFe", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("text");

                    b.Property<int>("Ambiente")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataRecepcao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EntidadeId")
                        .HasColumnType("text");

                    b.Property<int>("Modalidade")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StatusDistribuicao")
                        .HasColumnType("integer");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("DocumentId");

                    b.ToTable("NFes");
                });
#pragma warning restore 612, 618
        }
    }
}
